sudo: false

language: node_js

node_js:
  - "0.10.28"

env:
  global:
    - NODE_ENV=travis

services:
  - rabbitmq

addons:
  hosts:
    - rabbitmq

before_install:
  - npm install -g npm

install:
  - npm install

script:

  # Detect errors and potential problems
  - npm run jshint -- ./
  - npm run eslint -- --reset --eslintrc ./
  - npm run jscs -- ./

  # Check packages with known and public vulnerable dependencies
  - npm run nsp -- audit-package
  - npm run nsp -- audit-shrinkwrap

  # Run unit tests (and check for coverage)
  - npm test
